import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRole, ArcBridgeConfig } from "@arcbridge/core";
import type { PlatformAdapter } from "../types.js";

function generateClaudeMd(config: ArcBridgeConfig): string {
  const lines: string[] = [
    `# ${config.project_name}`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
    "## Project Overview",
    "",
    `- **Type:** ${config.project_type}`,
    `- **Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## Architecture",
    "",
    "This project uses arc42 documentation stored in `.arcbridge/arc42/`.",
    "Use the ArcBridge MCP tools to query architecture, building blocks, and quality scenarios.",
    "",
    "## Key Commands",
    "",
    "- `arcbridge_get_project_status` — Get current project status",
    "- `arcbridge_get_building_blocks` — View architecture building blocks",
    "- `arcbridge_get_quality_scenarios` — View quality requirements",
    "- `arcbridge_get_current_tasks` — View current phase tasks",
    "",
    "## Code Intelligence",
    "",
    "- `arcbridge_search_symbols` — Search for functions, classes, types in the codebase",
    "- `arcbridge_get_symbol` — Get full details on a symbol (signature, source, dependencies)",
    "- `arcbridge_get_dependency_graph` — Analyze module dependencies",
    "- `arcbridge_reindex` — Re-index TypeScript symbols after code changes",
    "",
    "## React & Next.js Analysis",
    "",
    "- `arcbridge_get_component_graph` — View component hierarchy, props, state, and context usage",
    "- `arcbridge_get_route_map` — View Next.js route tree (pages, layouts, API routes)",
    "- `arcbridge_get_boundary_analysis` — Analyze server/client boundaries and detect violations",
    "",
    "## Architecture Bridge",
    "",
    "- `arcbridge_check_drift` — Detect undocumented modules, missing code, and cross-block violations",
    "- `arcbridge_get_guidance` — Get context-aware guidance when making changes",
    "- `arcbridge_get_open_questions` — Surface architectural gaps and untested scenarios",
    "- `arcbridge_propose_arc42_update` — Generate specific arc42 update proposals from code changes",
    "- `arcbridge_get_practice_review` — Review recent changes across 5 dimensions",
    "",
    "## Agent Roles",
    "",
    "Available agent roles are defined in `.arcbridge/agents/` and `.claude/agents/`.",
    "",
  ];

  return lines.join("\n");
}

function generateAgentFile(role: AgentRole): string {
  const lines: string[] = [
    `# ${role.name}`,
    "",
    role.description,
    "",
    "## Tools",
    "",
    ...role.required_tools.map((t) => `- ${t}`),
    "",
  ];

  if (role.denied_tools.length > 0) {
    lines.push("## Denied Tools", "", ...role.denied_tools.map((t) => `- ${t}`), "");
  }

  if (role.read_only) {
    lines.push("## Access", "", "This role is **read-only**.", "");
  }

  if (role.quality_focus.length > 0) {
    lines.push(
      "## Quality Focus",
      "",
      ...role.quality_focus.map((q) => `- ${q}`),
      "",
    );
  }

  lines.push("## Instructions", "", role.system_prompt, "");

  return lines.join("\n");
}

export class ClaudeAdapter implements PlatformAdapter {
  platform = "claude";

  generateProjectConfig(targetDir: string, config: ArcBridgeConfig): void {
    const content = generateClaudeMd(config);
    writeFileSync(join(targetDir, "CLAUDE.md"), content, "utf-8");
  }

  generateAgentConfigs(targetDir: string, roles: AgentRole[]): void {
    const agentsDir = join(targetDir, ".claude", "agents");
    mkdirSync(agentsDir, { recursive: true });

    for (const role of roles) {
      const content = generateAgentFile(role);
      writeFileSync(join(agentsDir, `${role.role_id}.md`), content, "utf-8");
    }
  }
}
