import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRole, ArcBridgeConfig } from "@arcbridge/core";
import type { PlatformAdapter } from "../types.js";

function generateClaudeMd(config: ArcBridgeConfig): string {
  const lines: string[] = [
    `# ${config.project_name}`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
    "## Project Overview",
    "",
    `- **Type:** ${config.project_type}`,
    `- **Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## How to Work in This Project",
    "",
    "This project follows the **Plan → Build → Sync → Review** convention using ArcBridge.",
    "ArcBridge provides MCP tools that give you architectural awareness. **Use them throughout your work.**",
    "",
    "### Before Starting Any Work",
    "",
    "1. Check project status: `arcbridge_get_project_status`",
    "2. Review current tasks: `arcbridge_get_current_tasks`",
    "3. Activate the appropriate role (see below): `arcbridge_activate_role`",
    "",
    "### When Planning or Refining Architecture",
    "",
    "Activate the **architect** role: `arcbridge_activate_role({ role: \"architect\" })`",
    "",
    "Then use:",
    "- `arcbridge_get_building_blocks` — view current architecture decomposition",
    "- `arcbridge_get_quality_scenarios` — view quality requirements",
    "- `arcbridge_get_open_questions` — find architectural gaps to resolve",
    "- `arcbridge_propose_arc42_update` — propose doc updates from recent code changes",
    "",
    "### When Implementing Features",
    "",
    "Activate the **implementer** role: `arcbridge_activate_role({ role: \"implementer\" })`",
    "",
    "Then use:",
    "- `arcbridge_get_guidance` — get context-aware guidance for the file/block you're working on",
    "- `arcbridge_get_current_tasks` — check what tasks are expected in the current phase",
    "- `arcbridge_search_symbols` / `arcbridge_get_symbol` — understand existing code",
    "- `arcbridge_get_dependency_graph` — check module dependencies before adding new ones",
    "- `arcbridge_update_task` — mark tasks as in-progress or done as you complete them",
    "- `arcbridge_reindex` — re-index after significant code changes",
    "",
    "### After Implementing (Review)",
    "",
    "Before completing a phase, run reviews:",
    "",
    "1. **Drift check:** `arcbridge_check_drift` — catch undeclared dependencies and missing modules",
    "2. **Security review:** `arcbridge_activate_role({ role: \"security-reviewer\" })` then `arcbridge_run_role_check`",
    "3. **Quality review:** `arcbridge_activate_role({ role: \"quality-guardian\" })` then `arcbridge_get_practice_review`",
    "4. **Verify scenarios:** `arcbridge_verify_scenarios` — run linked tests for quality scenarios",
    "",
    "### Completing a Phase",
    "",
    "Activate the **phase-manager** role: `arcbridge_activate_role({ role: \"phase-manager\" })`",
    "",
    "Then: `arcbridge_complete_phase` — validates three gates: all tasks done, no critical drift, must-have quality scenarios not failing.",
    "",
  ];

  // Add React/Next.js section only for relevant project types
  if (config.project_type === "nextjs-app-router" || config.project_type === "react-vite") {
    lines.push(
      "## React & Next.js Analysis",
      "",
      "- `arcbridge_get_component_graph` — view component hierarchy, props, state, and context usage",
      "- `arcbridge_get_route_map` — view Next.js route tree (pages, layouts, API routes)",
      "- `arcbridge_get_boundary_analysis` — analyze server/client boundaries and detect violations",
      "",
    );
  }

  lines.push(
    "## Agent Roles",
    "",
    "Activate roles with `arcbridge_activate_role` to get specialized context and tool guidance:",
    "",
    "| Role | When to Use |",
    "|------|-------------|",
    "| `architect` | Defining building blocks, reviewing dependencies, creating ADRs |",
    "| `implementer` | Writing code within the established architecture |",
    "| `security-reviewer` | Auditing auth, input validation, client/server boundaries |",
    "| `quality-guardian` | Reviewing test coverage, quality scenarios, quality gates |",
    "| `phase-manager` | Completing phases, managing task transitions |",
    "| `code-reviewer` | Reviewing code for correctness, patterns, edge cases |",
    "| `onboarding` | Understanding the project (for new developers) |",
    "",
    "Roles are defined in `.arcbridge/agents/` and `.claude/agents/`.",
    "",
  );

  return lines.join("\n");
}

function generateAgentFile(role: AgentRole): string {
  const lines: string[] = [
    `# ${role.name}`,
    "",
    role.description,
    "",
    "## Tools",
    "",
    ...role.required_tools.map((t) => `- ${t}`),
    "",
  ];

  if (role.denied_tools.length > 0) {
    lines.push("## Denied Tools", "", ...role.denied_tools.map((t) => `- ${t}`), "");
  }

  if (role.read_only) {
    lines.push("## Access", "", "This role is **read-only**.", "");
  }

  if (role.quality_focus.length > 0) {
    lines.push(
      "## Quality Focus",
      "",
      ...role.quality_focus.map((q) => `- ${q}`),
      "",
    );
  }

  lines.push("## Instructions", "", role.system_prompt, "");

  return lines.join("\n");
}

export class ClaudeAdapter implements PlatformAdapter {
  platform = "claude";

  generateProjectConfig(targetDir: string, config: ArcBridgeConfig): void {
    const content = generateClaudeMd(config);
    writeFileSync(join(targetDir, "CLAUDE.md"), content, "utf-8");

    // Generate .mcp.json if it doesn't already exist
    const mcpJsonPath = join(targetDir, ".mcp.json");
    if (!existsSync(mcpJsonPath)) {
      const mcpConfig = {
        mcpServers: {
          arcbridge: {
            command: "npx",
            args: ["@arcbridge/mcp-server"],
          },
        },
      };
      writeFileSync(mcpJsonPath, JSON.stringify(mcpConfig, null, 2) + "\n", "utf-8");
    } else {
      // If .mcp.json exists, add arcbridge server if not already present
      try {
        const existing = JSON.parse(readFileSync(mcpJsonPath, "utf-8")) as {
          mcpServers?: Record<string, unknown>;
        };
        if (!existing.mcpServers?.arcbridge) {
          existing.mcpServers = existing.mcpServers ?? {};
          existing.mcpServers.arcbridge = {
            command: "npx",
            args: ["@arcbridge/mcp-server"],
          };
          writeFileSync(mcpJsonPath, JSON.stringify(existing, null, 2) + "\n", "utf-8");
        }
      } catch {
        // If we can't parse existing .mcp.json, leave it alone
      }
    }
  }

  generateAgentConfigs(targetDir: string, roles: AgentRole[]): void {
    const agentsDir = join(targetDir, ".claude", "agents");
    mkdirSync(agentsDir, { recursive: true });

    for (const role of roles) {
      const content = generateAgentFile(role);
      writeFileSync(join(agentsDir, `${role.role_id}.md`), content, "utf-8");
    }
  }
}
