import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRole, ArcBridgeConfig } from "@arcbridge/core";
import type { PlatformAdapter } from "../types.js";

function generateAgentsMd(config: ArcBridgeConfig): string {
  const lines: string[] = [
    `# ${config.project_name}`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
    "## Codex MCP Setup",
    "",
    "Add this to your `~/.codex/config.toml` (one-time setup):",
    "",
    "```toml",
    "[mcp_servers.arcbridge]",
    'command = "npx"',
    'args = ["-y", "@arcbridge/mcp-server"]',
    "```",
    "",
    "## Project Overview",
    "",
    `- **Type:** ${config.project_type}`,
    `- **Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## How to Work in This Project",
    "",
    "This project follows the **Plan → Build → Sync → Review** convention using ArcBridge.",
    "ArcBridge provides MCP tools that give you architectural awareness. **Use them throughout your work.**",
    "",
    "### Before Starting Any Work",
    "",
    "1. Check project status: `arcbridge_get_project_status`",
    "2. Review current tasks: `arcbridge_get_current_tasks`",
    "3. Activate the appropriate role: `arcbridge_activate_role`",
    "",
    "### When Planning or Refining Architecture",
    "",
    "Activate the **architect** role: `arcbridge_activate_role({ role: \"architect\" })`",
    "",
    "- `arcbridge_get_building_blocks` — view architecture decomposition",
    "- `arcbridge_get_quality_scenarios` — view quality requirements",
    "- `arcbridge_get_open_questions` — find architectural gaps",
    "- `arcbridge_propose_arc42_update` — propose doc updates from code changes",
    "",
    "### When Implementing Features",
    "",
    "Activate the **implementer** role: `arcbridge_activate_role({ role: \"implementer\" })`",
    "",
    "- `arcbridge_get_guidance` — context-aware guidance for the file/block you're working on",
    "- `arcbridge_get_current_tasks` — check expected tasks in the current phase",
    "- `arcbridge_search_symbols` / `arcbridge_get_symbol` — understand existing code",
    "- `arcbridge_get_dependency_graph` — check module dependencies",
    "- `arcbridge_update_task` — mark tasks as in-progress or done",
    "- `arcbridge_reindex` — re-index after significant code changes",
    "",
    "### After Implementing (Phase Boundary Review)",
    "",
    "Before completing a phase:",
    "",
    "1. **Drift check:** `arcbridge_check_drift` — catch undeclared dependencies",
    "2. **Verify scenarios:** `arcbridge_verify_scenarios` — run linked quality tests",
    "3. **Practice review:** `arcbridge_get_practice_review` — review across 5 dimensions",
    "",
    "### Completing a Phase",
    "",
    "Activate the **phase-manager** role, then: `arcbridge_complete_phase`",
    "— validates three gates: all tasks done, no critical drift, must-have quality scenarios (priority = \"must\") not failing.",
    "",
  ];

  // Add React/Next.js section only for relevant project types
  if (config.project_type === "nextjs-app-router" || config.project_type === "react-vite") {
    lines.push(
      "## React & Next.js Analysis",
      "",
      "- `arcbridge_get_component_graph` — component hierarchy, props, state, context",
      "- `arcbridge_get_route_map` — Next.js route tree (pages, layouts, API routes)",
      "- `arcbridge_get_boundary_analysis` — server/client boundary analysis",
      "",
    );
  }

  lines.push(
    "## Agent Roles",
    "",
    "Activate roles with `arcbridge_activate_role` to get specialized context.",
    "Roles are defined in `.arcbridge/agents/`.",
    "",
    "*Role table is appended below after agent configs are generated.*",
    "",
  );

  return lines.join("\n");
}

function generateSyncSkill(): string {
  return `---
name: arcbridge-sync
description: Run the ArcBridge sync loop — reindex code, detect architecture drift, and update task statuses. Use after significant code changes or before completing a phase.
---

# ArcBridge Sync

Run the full sync loop to keep architecture docs and task statuses in sync with code changes.

## Steps

1. **Reindex** — \`arcbridge_reindex\` to update the symbol index with recent code changes
2. **Check drift** — \`arcbridge_check_drift\` to detect undeclared dependencies and missing modules
3. **Review tasks** — \`arcbridge_get_current_tasks\` to see if any tasks can be inferred as done
4. **Propose updates** — \`arcbridge_propose_arc42_update\` to generate documentation update proposals

## When to Use

- After completing a significant feature or refactoring
- Before running \`arcbridge_complete_phase\`
- When you suspect architecture docs are out of date
- Periodically during active development
`;
}

function generateReviewSkill(): string {
  return `---
name: arcbridge-review
description: Run ArcBridge phase boundary reviews — drift check, quality scenario verification, and practice review across 5 dimensions. Use before completing a phase.
---

# ArcBridge Phase Review

Run the full review suite before completing a phase gate.

## Steps

1. **Drift check** — \`arcbridge_check_drift\` to catch undeclared dependencies and boundary violations
2. **Verify scenarios** — \`arcbridge_verify_scenarios\` to run linked tests for quality scenarios
3. **Practice review** — \`arcbridge_get_practice_review\` to review changes across architecture, security, testing, docs, and complexity
4. **Role checks** — optionally run \`arcbridge_run_role_check\` with specific roles (security-reviewer, quality-guardian)
5. **Complete phase** — if all checks pass, run \`arcbridge_complete_phase\` to validate gates and transition

## Review Roles

| Role | When to consult |
|------|----------------|
| **code-reviewer** | Every phase |
| **security-reviewer** | Phases with auth, uploads, API routes, user input |
| **quality-guardian** | Every 2nd phase, or when quality scenarios are linked |
| **architect** | When drift is detected or architecture evolved significantly |
`;
}

export class CodexAdapter implements PlatformAdapter {
  platform = "codex";

  generateProjectConfig(targetDir: string, config: ArcBridgeConfig): void {
    const agentsMdContent = generateAgentsMd(config);
    const agentsMdPath = join(targetDir, "AGENTS.md");
    const marker = "<!-- arcbridge-generated -->";

    if (existsSync(agentsMdPath)) {
      const existing = readFileSync(agentsMdPath, "utf-8");
      const markerIndex = existing.indexOf(marker);

      if (markerIndex >= 0) {
        // Replace everything from the marker onwards
        const userContent = existing.slice(0, markerIndex).trimEnd();
        const prefix = userContent ? `${userContent}\n\n` : "";
        writeFileSync(agentsMdPath, `${prefix}${marker}\n\n${agentsMdContent}`, "utf-8");
      } else {
        // No existing ArcBridge content — append
        const existingTrimmed = existing.trimEnd();
        const prefix = existingTrimmed ? `${existingTrimmed}\n\n` : "";
        writeFileSync(agentsMdPath, `${prefix}${marker}\n\n${agentsMdContent}`, "utf-8");
      }
    } else {
      writeFileSync(agentsMdPath, `${marker}\n\n${agentsMdContent}`, "utf-8");
    }
  }

  generateAgentConfigs(targetDir: string, roles: AgentRole[]): void {
    // Append dynamic role table to AGENTS.md (replaces placeholder)
    const agentsMdPath = join(targetDir, "AGENTS.md");
    if (existsSync(agentsMdPath)) {
      let content = readFileSync(agentsMdPath, "utf-8");
      const roleTable = [
        "| Role | Description |",
        "|------|-------------|",
        ...roles.map((r) => `| \`${r.role_id}\` | ${r.description} |`),
        "",
      ].join("\n");

      const placeholder = "*Role table is appended below after agent configs are generated.*";
      if (content.includes(placeholder)) {
        content = content.replace(placeholder, roleTable);
      } else {
        // Fallback: append role table at the end if placeholder was removed
        content = `${content.trimEnd()}\n\n## Agent Roles\n\n${roleTable}\n`;
      }
      writeFileSync(agentsMdPath, content, "utf-8");
    }

    // Generate skills (reusable workflows) instead of per-role agent files,
    // since Codex agent definitions live in the global ~/.codex/config.toml
    const skillsDir = join(targetDir, ".agents", "skills");

    const syncDir = join(skillsDir, "arcbridge-sync");
    mkdirSync(syncDir, { recursive: true });
    writeFileSync(join(syncDir, "SKILL.md"), generateSyncSkill(), "utf-8");

    const reviewDir = join(skillsDir, "arcbridge-review");
    mkdirSync(reviewDir, { recursive: true });
    writeFileSync(join(reviewDir, "SKILL.md"), generateReviewSkill(), "utf-8");
  }
}
