import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRole, ArcBridgeConfig } from "@arcbridge/core";
import type { PlatformAdapter } from "../types.js";
import { generateSkills } from "../shared/skills.js";

function generateAgentsMd(config: ArcBridgeConfig): string {
  const lines: string[] = [
    `# ${config.project_name}`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
    "## Codex MCP Setup",
    "",
    "Add this to your `~/.codex/config.toml` (one-time setup):",
    "",
    "```toml",
    "[mcp_servers.arcbridge]",
    'command = "npx"',
    'args = ["-y", "@arcbridge/mcp-server"]',
    "```",
    "",
    "## Project Overview",
    "",
    `- **Type:** ${config.project_type}`,
    `- **Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## How to Work in This Project",
    "",
    "This project follows the **Plan → Build → Sync → Review** convention using ArcBridge.",
    "ArcBridge provides MCP tools that give you architectural awareness. **Use them throughout your work.**",
    "",
    "### Before Starting Any Work",
    "",
    "1. Check project status: `arcbridge_get_project_status`",
    "2. Review current tasks: `arcbridge_get_current_tasks`",
    "3. Activate the appropriate role: `arcbridge_activate_role`",
    "",
    "### When Planning or Refining Architecture",
    "",
    "Activate the **architect** role: `arcbridge_activate_role({ role: \"architect\" })`",
    "",
    "- `arcbridge_get_building_blocks` — view architecture decomposition",
    "- `arcbridge_get_quality_scenarios` — view quality requirements",
    "- `arcbridge_get_open_questions` — find architectural gaps",
    "- `arcbridge_propose_arc42_update` — propose doc updates from code changes",
    "",
    "### When Implementing Features",
    "",
    "Activate the **implementer** role: `arcbridge_activate_role({ role: \"implementer\" })`",
    "",
    "- `arcbridge_get_guidance` — context-aware guidance for the file/block you're working on",
    "- `arcbridge_get_current_tasks` — check expected tasks in the current phase",
    "- `arcbridge_search_symbols` / `arcbridge_get_symbol` — understand existing code",
    "- `arcbridge_get_dependency_graph` — check module dependencies",
    "- `arcbridge_update_task` — mark tasks as in-progress or done",
    "- `arcbridge_reindex` — re-index after significant code changes",
    "",
    "### After Implementing (Phase Boundary Review)",
    "",
    "Before completing a phase:",
    "",
    "1. **Drift check:** `arcbridge_check_drift` — catch undeclared dependencies",
    "2. **Verify scenarios:** `arcbridge_verify_scenarios` — run linked quality tests",
    "3. **Practice review:** `arcbridge_get_practice_review` — review across 5 dimensions",
    "",
    "### Completing a Phase",
    "",
    "Activate the **phase-manager** role, then: `arcbridge_complete_phase`",
    "— validates three gates: all tasks done, no critical drift, must-have quality scenarios (priority = \"must\") not failing.",
    "",
  ];

  // Add React/Next.js section only for relevant project types
  if (config.project_type === "nextjs-app-router" || config.project_type === "react-vite") {
    lines.push(
      "## React & Next.js Analysis",
      "",
      "- `arcbridge_get_component_graph` — component hierarchy, props, state, context",
      "- `arcbridge_get_route_map` — Next.js route tree (pages, layouts, API routes)",
      "- `arcbridge_get_boundary_analysis` — server/client boundary analysis",
      "",
    );
  }

  lines.push(
    "## Agent Roles",
    "",
    "Activate roles with `arcbridge_activate_role` to get specialized context.",
    "Roles are defined in `.arcbridge/agents/`.",
    "",
    "*Role table is appended below after agent configs are generated.*",
    "",
  );

  return lines.join("\n");
}

export class CodexAdapter implements PlatformAdapter {
  platform = "codex";

  generateProjectConfig(targetDir: string, config: ArcBridgeConfig): void {
    const agentsMdContent = generateAgentsMd(config);
    const agentsMdPath = join(targetDir, "AGENTS.md");
    const marker = "<!-- arcbridge-generated -->";

    if (existsSync(agentsMdPath)) {
      const existing = readFileSync(agentsMdPath, "utf-8");
      const markerIndex = existing.indexOf(marker);

      if (markerIndex >= 0) {
        // Replace everything from the marker onwards
        const userContent = existing.slice(0, markerIndex).trimEnd();
        const prefix = userContent ? `${userContent}\n\n` : "";
        writeFileSync(agentsMdPath, `${prefix}${marker}\n\n${agentsMdContent}`, "utf-8");
      } else {
        // No existing ArcBridge content — append
        const existingTrimmed = existing.trimEnd();
        const prefix = existingTrimmed ? `${existingTrimmed}\n\n` : "";
        writeFileSync(agentsMdPath, `${prefix}${marker}\n\n${agentsMdContent}`, "utf-8");
      }
    } else {
      writeFileSync(agentsMdPath, `${marker}\n\n${agentsMdContent}`, "utf-8");
    }
  }

  generateAgentConfigs(targetDir: string, roles: AgentRole[]): void {
    // Append dynamic role table to AGENTS.md (replaces placeholder)
    const agentsMdPath = join(targetDir, "AGENTS.md");
    if (existsSync(agentsMdPath)) {
      let content = readFileSync(agentsMdPath, "utf-8");
      const roleTable = [
        "| Role | Description |",
        "|------|-------------|",
        ...roles.map((r) => `| \`${r.role_id}\` | ${r.description} |`),
        "",
      ].join("\n");

      const placeholder = "*Role table is appended below after agent configs are generated.*";
      if (content.includes(placeholder)) {
        content = content.replace(placeholder, roleTable);
      } else {
        // Fallback: append role table at the end if placeholder was removed
        content = `${content.trimEnd()}\n\n## Agent Roles\n\n${roleTable}\n`;
      }
      writeFileSync(agentsMdPath, content, "utf-8");
    }

    // Generate missing skills (shared with Gemini adapter — only writes if not present)
    generateSkills(targetDir);
  }
}
