import type { ArcBridgeConfig } from "../../schemas/config.js";
import type { GeneratedFile } from "./claude-skill.js";

/**
 * Generate the GitHub Action workflow for automated ArcBridge sync.
 *
 * Deliberately installs NOTHING. It used to run `pnpm install --frozen-lockfile`
 * at the repo root, which fails outright unless the repo happens to be a pnpm
 * workspace rooted at the top — so it broke on plain npm projects, .NET-only and
 * Unity projects, and any monorepo whose Node package is nested (a fullstack
 * layout has no root package.json at all). The steps below invoke the published
 * CLI through `npx`, so there is nothing to install.
 */
export function githubActionTemplate(_config: ArcBridgeConfig): GeneratedFile {
  const content = `name: ArcBridge Sync

on:
  # Run on push to main branch
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.arcbridge/arc42/**'

  # Run weekly
  schedule:
    - cron: '0 9 * * 1'  # Monday 9am UTC

  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git diff analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Check for ArcBridge
        id: check
        run: |
          if [ -f ".arcbridge/config.yaml" ]; then
            echo "initialized=true" >> $GITHUB_OUTPUT
          else
            echo "initialized=false" >> $GITHUB_OUTPUT
            echo "::warning::ArcBridge is not initialized. Run arcbridge_init_project first."
          fi

      - name: Run ArcBridge sync
        if: steps.check.outputs.initialized == 'true'
        id: sync
        run: npx arcbridge sync --json | tee arcbridge-sync-result.json

      - name: Check for drift errors
        if: steps.check.outputs.initialized == 'true'
        run: |
          # --reindex is required: .arcbridge/index.db is gitignored, so a CI
          # checkout has no index. Without it, every building block's code_paths
          # and every ADR's files look absent and drift reports a pile of false
          # missing_module / stale_adr findings.
          npx arcbridge drift --reindex --json | tee arcbridge-drift-result.json
          ERRORS=$(node -e "try { const d=JSON.parse(require('fs').readFileSync('arcbridge-drift-result.json','utf8')); console.log(d.drift.filter(e=>e.severity==='error').length); } catch { console.log(0); }")
          if [ "$ERRORS" -gt 0 ]; then
            echo "::error::ArcBridge detected $ERRORS drift error(s) that would block phase completion."
            exit 1
          fi

      - name: Create sync PR
        if: steps.check.outputs.initialized == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: arcbridge sync - update arc42 documentation'
          title: 'ArcBridge Sync: Arc42 Documentation Updates'
          body: |
            ## ArcBridge Sync

            Automated architecture sync detected changes that may require documentation updates.

            **Review the proposed changes to \`.arcbridge/arc42/\` files.**

            ---
            *Generated by [ArcBridge](https://github.com/bifteki-crew/arcbridge) sync loop*
          branch: arcbridge/sync
          delete-branch: true
          labels: arcbridge,documentation
`;

  return {
    relativePath: ".github/workflows/arcbridge-sync.yml",
    content,
  };
}
