import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRole, ArcBridgeConfig } from "@arcbridge/core";
import type { PlatformAdapter } from "../types.js";

function generateStyleguide(config: ArcBridgeConfig): string {
  const lines: string[] = [
    `# ${config.project_name}`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
    "## Project Overview",
    "",
    `- **Type:** ${config.project_type}`,
    `- **Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## How to Work in This Project",
    "",
    "This project follows the **Plan → Build → Sync → Review** convention using ArcBridge.",
    "ArcBridge provides MCP tools that give you architectural awareness. **Use them throughout your work.**",
    "",
    "### Before Starting Any Work",
    "",
    "1. Check project status: `arcbridge_get_project_status`",
    "2. Review current tasks: `arcbridge_get_current_tasks`",
    "3. Activate the appropriate role: `arcbridge_activate_role`",
    "",
    "### When Planning or Refining Architecture",
    "",
    "Activate the **architect** role: `arcbridge_activate_role({ role: \"architect\" })`",
    "",
    "- `arcbridge_get_building_blocks` — view architecture decomposition",
    "- `arcbridge_get_quality_scenarios` — view quality requirements",
    "- `arcbridge_get_open_questions` — find architectural gaps",
    "- `arcbridge_propose_arc42_update` — propose doc updates from code changes",
    "",
    "### When Implementing Features",
    "",
    "Activate the **implementer** role: `arcbridge_activate_role({ role: \"implementer\" })`",
    "",
    "- `arcbridge_get_guidance` — context-aware guidance for the file/block you're working on",
    "- `arcbridge_get_current_tasks` — check expected tasks in the current phase",
    "- `arcbridge_search_symbols` / `arcbridge_get_symbol` — understand existing code",
    "- `arcbridge_get_dependency_graph` — check module dependencies",
    "- `arcbridge_update_task` — mark tasks as in-progress or done",
    "- `arcbridge_reindex` — re-index after significant code changes",
    "",
    "### After Implementing (Phase Boundary Review)",
    "",
    "Before completing a phase:",
    "",
    "1. **Drift check:** `arcbridge_check_drift` — catch undeclared dependencies",
    "2. **Verify scenarios:** `arcbridge_verify_scenarios` — run linked quality tests",
    "3. **Practice review:** `arcbridge_get_practice_review` — review across 5 dimensions",
    "",
    "### Completing a Phase",
    "",
    "Activate the **phase-manager** role, then: `arcbridge_complete_phase`",
    "— validates three gates: all tasks done, no critical drift, must-have quality scenarios (priority = \"must\") not failing.",
    "",
  ];

  if (config.project_type === "nextjs-app-router" || config.project_type === "react-vite") {
    lines.push(
      "## React & Next.js Analysis",
      "",
      "- `arcbridge_get_component_graph` — component hierarchy, props, state, context",
      "- `arcbridge_get_route_map` — Next.js route tree (pages, layouts, API routes)",
      "- `arcbridge_get_boundary_analysis` — server/client boundary analysis",
      "",
    );
  }

  return lines.join("\n");
}

function generateSettingsJson(): string {
  const settings = {
    mcpServers: {
      arcbridge: {
        command: "npx",
        args: ["-y", "@arcbridge/mcp-server"],
      },
    },
  };
  return JSON.stringify(settings, null, 2) + "\n";
}

function generateAgentFile(role: AgentRole): string {
  const lines: string[] = [
    "---",
    `name: ${role.role_id}`,
    `description: ${role.description}`,
  ];

  // Build single tools list (MCP tools + read-only file tools if applicable)
  const tools: string[] = role.required_tools.map(
    (tool) => `mcp_arcbridge_${tool.replace("arcbridge_", "")}`,
  );
  if (role.read_only) {
    tools.push("read_file", "grep_search", "list_directory");
  }
  if (tools.length > 0) {
    lines.push("tools:");
    for (const tool of tools) {
      lines.push(`  - ${tool}`);
    }
  }

  if (role.model_preferences.reasoning_depth === "high") {
    lines.push("model: gemini-2.5-pro");
  }

  lines.push("---", "");
  lines.push(role.system_prompt, "");

  return lines.join("\n");
}

export class GeminiAdapter implements PlatformAdapter {
  platform = "gemini";

  generateProjectConfig(targetDir: string, config: ArcBridgeConfig): void {
    const geminiDir = join(targetDir, ".gemini");
    mkdirSync(geminiDir, { recursive: true });

    // Generate .gemini/settings.json (MCP config)
    const settingsPath = join(geminiDir, "settings.json");
    if (!existsSync(settingsPath)) {
      writeFileSync(settingsPath, generateSettingsJson(), "utf-8");
    } else {
      // Add arcbridge MCP server if not already present
      try {
        const existing = JSON.parse(readFileSync(settingsPath, "utf-8")) as {
          mcpServers?: Record<string, unknown>;
        };
        if (!existing.mcpServers?.arcbridge) {
          existing.mcpServers = existing.mcpServers ?? {};
          existing.mcpServers.arcbridge = {
            command: "npx",
            args: ["-y", "@arcbridge/mcp-server"],
          };
          writeFileSync(settingsPath, JSON.stringify(existing, null, 2) + "\n", "utf-8");
        }
      } catch {
        // Can't parse existing settings.json — leave it alone
      }
    }

    // Generate .gemini/styleguide.md
    const styleguideContent = generateStyleguide(config);
    const styleguidePath = join(geminiDir, "styleguide.md");
    const marker = "<!-- arcbridge-generated -->";

    if (existsSync(styleguidePath)) {
      const existing = readFileSync(styleguidePath, "utf-8");
      const markerIndex = existing.indexOf(marker);

      if (markerIndex >= 0) {
        const userContent = existing.slice(0, markerIndex).trimEnd();
        const prefix = userContent ? `${userContent}\n\n` : "";
        writeFileSync(styleguidePath, `${prefix}${marker}\n\n${styleguideContent}`, "utf-8");
      } else {
        const existingTrimmed = existing.trimEnd();
        const prefix = existingTrimmed ? `${existingTrimmed}\n\n` : "";
        writeFileSync(styleguidePath, `${prefix}${marker}\n\n${styleguideContent}`, "utf-8");
      }
    } else {
      writeFileSync(styleguidePath, `${marker}\n\n${styleguideContent}`, "utf-8");
    }

    // Generate GEMINI.md (for Gemini CLI — same content as styleguide)
    const geminiMdPath = join(targetDir, "GEMINI.md");
    if (existsSync(geminiMdPath)) {
      const existing = readFileSync(geminiMdPath, "utf-8");
      const markerIndex = existing.indexOf(marker);

      if (markerIndex >= 0) {
        const userContent = existing.slice(0, markerIndex).trimEnd();
        const prefix = userContent ? `${userContent}\n\n` : "";
        writeFileSync(geminiMdPath, `${prefix}${marker}\n\n${styleguideContent}`, "utf-8");
      } else {
        const existingTrimmed = existing.trimEnd();
        const prefix = existingTrimmed ? `${existingTrimmed}\n\n` : "";
        writeFileSync(geminiMdPath, `${prefix}${marker}\n\n${styleguideContent}`, "utf-8");
      }
    } else {
      writeFileSync(geminiMdPath, `${marker}\n\n${styleguideContent}`, "utf-8");
    }
  }

  generateAgentConfigs(targetDir: string, roles: AgentRole[]): void {
    // Generate .gemini/agents/*.md (Gemini subagents mapped from ArcBridge roles)
    const agentsDir = join(targetDir, ".gemini", "agents");
    mkdirSync(agentsDir, { recursive: true });

    for (const role of roles) {
      const content = generateAgentFile(role);
      writeFileSync(join(agentsDir, `${role.role_id}.md`), content, "utf-8");
    }

    // Skills are generated by the Codex adapter at .agents/skills/ —
    // Gemini CLI supports this path as a first-class alias, so no
    // duplication needed. Generate any missing skills.
    const skillsDir = join(targetDir, ".agents", "skills");
    const syncMissing = !existsSync(join(skillsDir, "arcbridge-sync", "SKILL.md"));
    const reviewMissing = !existsSync(join(skillsDir, "arcbridge-review", "SKILL.md"));
    if (syncMissing || reviewMissing) {
      this.generateSkills(targetDir);
    }
  }

  private generateSkills(targetDir: string): void {
    const skillsDir = join(targetDir, ".agents", "skills");

    const syncDir = join(skillsDir, "arcbridge-sync");
    mkdirSync(syncDir, { recursive: true });
    writeFileSync(join(syncDir, "SKILL.md"), `---
name: arcbridge-sync
description: Run the ArcBridge sync loop — reindex code, detect architecture drift, and update task statuses. Use after significant code changes or before completing a phase.
---

# ArcBridge Sync

Run the full sync loop to keep architecture docs and task statuses in sync with code changes.

## Steps

1. **Reindex** — \`arcbridge_reindex\` to update the symbol index with recent code changes
2. **Check drift** — \`arcbridge_check_drift\` to detect undeclared dependencies and missing modules
3. **Review tasks** — \`arcbridge_get_current_tasks\` to see if any tasks can be inferred as done
4. **Propose updates** — \`arcbridge_propose_arc42_update\` to generate documentation update proposals
`, "utf-8");

    const reviewDir = join(skillsDir, "arcbridge-review");
    mkdirSync(reviewDir, { recursive: true });
    writeFileSync(join(reviewDir, "SKILL.md"), `---
name: arcbridge-review
description: Run ArcBridge phase boundary reviews — drift check, quality scenario verification, and practice review across 5 dimensions. Use before completing a phase.
---

# ArcBridge Phase Review

Run the full review suite before completing a phase gate.

## Steps

1. **Drift check** — \`arcbridge_check_drift\` to catch undeclared dependencies and boundary violations
2. **Verify scenarios** — \`arcbridge_verify_scenarios\` to run linked tests for quality scenarios
3. **Practice review** — \`arcbridge_get_practice_review\` to review changes across architecture, security, testing, docs, and complexity
4. **Role checks** — optionally run \`arcbridge_run_role_check\` with specific roles (security-reviewer, quality-guardian)
5. **Complete phase** — if all checks pass, run \`arcbridge_complete_phase\` to validate gates and transition
`, "utf-8");
  }
}
