import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRole, ArcBridgeConfig } from "@arcbridge/core";
import type { PlatformAdapter } from "../types.js";

function generateCopilotInstructions(config: ArcBridgeConfig): string {
  const lines: string[] = [
    `# ${config.project_name} - Copilot Instructions`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
    "## Project Context",
    "",
    `This is a ${config.project_type} project.`,
    "",
    `**Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## Architecture",
    "",
    "Architecture documentation is in `.arcbridge/arc42/`.",
    "Quality scenarios are in `.arcbridge/arc42/10-quality-scenarios.yaml`.",
    "Phase plan is in `.arcbridge/plan/`.",
    "",
    "## Code Intelligence",
    "",
    "Use ArcBridge MCP tools to explore the codebase:",
    "- `arcbridge_search_symbols` — Search for functions, classes, types",
    "- `arcbridge_get_symbol` — Get full details on a symbol",
    "- `arcbridge_get_dependency_graph` — Analyze module dependencies",
    "- `arcbridge_reindex` — Re-index after code changes",
    "",
    "## React & Next.js Analysis",
    "",
    "- `arcbridge_get_component_graph` — View component hierarchy, props, state, and context",
    "- `arcbridge_get_route_map` — View Next.js route tree (pages, layouts, API routes)",
    "- `arcbridge_get_boundary_analysis` — Analyze server/client boundaries",
    "",
    "## Architecture Bridge",
    "",
    "- `arcbridge_check_drift` — Detect architecture drift and boundary violations",
    "- `arcbridge_get_guidance` — Get context-aware guidance for code changes",
    "- `arcbridge_get_open_questions` — Surface architectural gaps",
    "- `arcbridge_propose_arc42_update` — Generate arc42 update proposals from code changes",
    "- `arcbridge_get_practice_review` — Review recent changes across 5 practice dimensions",
    "",
    "## Conventions",
    "",
    "- Follow existing patterns in the codebase",
    "- Stay within building block boundaries",
    "- Write tests for new functionality",
    "- Check quality scenarios before submitting changes",
    "",
  ];

  return lines.join("\n");
}

function generateAgentFile(role: AgentRole): string {
  const lines: string[] = [
    `# ${role.name}`,
    "",
    role.description,
    "",
  ];

  if (role.read_only) {
    lines.push("**Access:** Read-only", "");
  }

  if (role.quality_focus.length > 0) {
    lines.push(
      "## Quality Focus",
      "",
      ...role.quality_focus.map((q) => `- ${q}`),
      "",
    );
  }

  lines.push("## Instructions", "", role.system_prompt, "");

  return lines.join("\n");
}

export class CopilotAdapter implements PlatformAdapter {
  platform = "copilot";

  generateProjectConfig(targetDir: string, config: ArcBridgeConfig): void {
    const githubDir = join(targetDir, ".github");
    mkdirSync(githubDir, { recursive: true });

    const content = generateCopilotInstructions(config);
    writeFileSync(
      join(githubDir, "copilot-instructions.md"),
      content,
      "utf-8",
    );
  }

  generateAgentConfigs(targetDir: string, roles: AgentRole[]): void {
    const agentsDir = join(targetDir, ".github", "agents");
    mkdirSync(agentsDir, { recursive: true });

    for (const role of roles) {
      const content = generateAgentFile(role);
      writeFileSync(join(agentsDir, `${role.role_id}.md`), content, "utf-8");
    }
  }
}
