import type { ArcBridgeConfig } from "@arcbridge/core";

export interface InstructionOptions {
  /** Lines to prepend before the shared workflow section (after project overview) */
  prefix?: string[];
  /** Lines to append after the shared workflow section */
  suffix?: string[];
}

/**
 * Generate the shared ArcBridge workflow instructions.
 * Used by Gemini, OpenCode, and Codex adapters. Claude uses its own
 * variant with platform-specific wording.
 */
export function generateInstructions(config: ArcBridgeConfig, options?: InstructionOptions): string {
  const lines: string[] = [
    `# ${config.project_name}`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
  ];

  if (options?.prefix) {
    lines.push(...options.prefix);
  }

  lines.push(
    "## Project Overview",
    "",
    `- **Type:** ${config.project_type}`,
    `- **Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## How to Work in This Project",
    "",
    "This project follows the **Plan → Build → Sync → Review** convention using ArcBridge.",
    "ArcBridge provides MCP tools that give you architectural awareness. **Use them throughout your work.**",
    "",
    "### Before Starting Any Work",
    "",
    "1. Check project status: `arcbridge_get_project_status`",
    "2. Review current tasks: `arcbridge_get_current_tasks`",
    "3. Activate the appropriate role: `arcbridge_activate_role`",
    "",
    "### When Planning or Refining Architecture",
    "",
    "Activate the **architect** role: `arcbridge_activate_role({ role: \"architect\" })`",
    "",
    "- `arcbridge_get_building_blocks` — view architecture decomposition",
    "- `arcbridge_get_quality_scenarios` — view quality requirements",
    "- `arcbridge_get_open_questions` — find architectural gaps",
    "- `arcbridge_propose_arc42_update` — propose doc updates from code changes",
    "",
    "### When Implementing Features",
    "",
    "Activate the **implementer** role: `arcbridge_activate_role({ role: \"implementer\" })`",
    "",
    "- `arcbridge_get_guidance` — context-aware guidance for the file/block you're working on",
    "- `arcbridge_get_current_tasks` — check expected tasks in the current phase",
    "- `arcbridge_search_symbols` / `arcbridge_get_symbol` — understand existing code",
    "- `arcbridge_get_dependency_graph` — check module dependencies",
    "- `arcbridge_update_task` — mark tasks as in-progress or done",
    "- `arcbridge_reindex` — re-index after significant code changes",
    "",
    "### After Implementing (Phase Boundary Review)",
    "",
    "Before completing a phase:",
    "",
    "1. **Drift check:** `arcbridge_check_drift` — catch undeclared dependencies",
    "2. **Verify scenarios:** `arcbridge_verify_scenarios` — run linked quality tests",
    "3. **Practice review:** `arcbridge_get_practice_review` — review across 5 dimensions",
    "",
    "### Completing a Phase",
    "",
    "Activate the **phase-manager** role, then: `arcbridge_complete_phase`",
    "— validates three gates: all tasks done, no critical drift, must-have quality scenarios (priority = \"must\") not failing.",
    "",
  );

  if (config.project_type === "nextjs-app-router" || config.project_type === "react-vite") {
    lines.push(
      "## React & Next.js Analysis",
      "",
      "- `arcbridge_get_component_graph` — component hierarchy, props, state, context",
      "- `arcbridge_get_route_map` — Next.js route tree (pages, layouts, API routes)",
      "- `arcbridge_get_boundary_analysis` — server/client boundary analysis",
      "",
    );
  }

  if (options?.suffix) {
    lines.push(...options.suffix);
  }

  return lines.join("\n");
}
