import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRole, ArcBridgeConfig } from "@arcbridge/core";
import type { PlatformAdapter, AdapterOptions } from "../types.js";
import { generateSkills } from "../shared/skills.js";

const MARKER = "<!-- arcbridge-generated -->";

/** Write content to a file with marker-based merge (preserves user content above marker) */
function writeWithMarkerMerge(filePath: string, content: string): void {
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, "utf-8");
    const markerIndex = existing.indexOf(MARKER);

    if (markerIndex >= 0) {
      const userContent = existing.slice(0, markerIndex).trimEnd();
      const prefix = userContent ? `${userContent}\n\n` : "";
      writeFileSync(filePath, `${prefix}${MARKER}\n\n${content}`, "utf-8");
    } else {
      const existingTrimmed = existing.trimEnd();
      const prefix = existingTrimmed ? `${existingTrimmed}\n\n` : "";
      writeFileSync(filePath, `${prefix}${MARKER}\n\n${content}`, "utf-8");
    }
  } else {
    writeFileSync(filePath, `${MARKER}\n\n${content}`, "utf-8");
  }
}

function generateInstructions(config: ArcBridgeConfig): string {
  const lines: string[] = [
    `# ${config.project_name}`,
    "",
    `> Auto-generated by ArcBridge. Edit .arcbridge/ files to update.`,
    "",
    "## Project Overview",
    "",
    `- **Type:** ${config.project_type}`,
    `- **Quality Priorities:** ${config.quality_priorities.join(", ")}`,
    "",
    "## How to Work in This Project",
    "",
    "This project follows the **Plan → Build → Sync → Review** convention using ArcBridge.",
    "ArcBridge provides MCP tools that give you architectural awareness. **Use them throughout your work.**",
    "",
    "### Before Starting Any Work",
    "",
    "1. Check project status: `arcbridge_get_project_status`",
    "2. Review current tasks: `arcbridge_get_current_tasks`",
    "3. Activate the appropriate role: `arcbridge_activate_role`",
    "",
    "### When Planning or Refining Architecture",
    "",
    "Activate the **architect** role: `arcbridge_activate_role({ role: \"architect\" })`",
    "",
    "- `arcbridge_get_building_blocks` — view architecture decomposition",
    "- `arcbridge_get_quality_scenarios` — view quality requirements",
    "- `arcbridge_get_open_questions` — find architectural gaps",
    "- `arcbridge_propose_arc42_update` — propose doc updates from code changes",
    "",
    "### When Implementing Features",
    "",
    "Activate the **implementer** role: `arcbridge_activate_role({ role: \"implementer\" })`",
    "",
    "- `arcbridge_get_guidance` — context-aware guidance for the file/block you're working on",
    "- `arcbridge_get_current_tasks` — check expected tasks in the current phase",
    "- `arcbridge_search_symbols` / `arcbridge_get_symbol` — understand existing code",
    "- `arcbridge_get_dependency_graph` — check module dependencies",
    "- `arcbridge_update_task` — mark tasks as in-progress or done",
    "- `arcbridge_reindex` — re-index after significant code changes",
    "",
    "### After Implementing (Phase Boundary Review)",
    "",
    "Before completing a phase:",
    "",
    "1. **Drift check:** `arcbridge_check_drift` — catch undeclared dependencies",
    "2. **Verify scenarios:** `arcbridge_verify_scenarios` — run linked quality tests",
    "3. **Practice review:** `arcbridge_get_practice_review` — review across 5 dimensions",
    "",
    "### Completing a Phase",
    "",
    "Activate the **phase-manager** role, then: `arcbridge_complete_phase`",
    "— validates three gates: all tasks done, no critical drift, must-have quality scenarios (priority = \"must\") not failing.",
    "",
  ];

  if (config.project_type === "nextjs-app-router" || config.project_type === "react-vite") {
    lines.push(
      "## React & Next.js Analysis",
      "",
      "- `arcbridge_get_component_graph` — component hierarchy, props, state, context",
      "- `arcbridge_get_route_map` — Next.js route tree (pages, layouts, API routes)",
      "- `arcbridge_get_boundary_analysis` — server/client boundary analysis",
      "",
    );
  }

  return lines.join("\n");
}

function generateOpenCodeJson(): string {
  const config = {
    $schema: "https://opencode.ai/config.json",
    instructions: ["OPENCODE.md"],
    mcp: {
      arcbridge: {
        type: "local",
        command: ["npx", "-y", "@arcbridge/mcp-server"],
      },
    },
  };
  return JSON.stringify(config, null, 2) + "\n";
}

function yamlQuote(value: string): string {
  if (/[:#{}&*!|>'"%@`\n]/.test(value) || value !== value.trim()) {
    return JSON.stringify(value);
  }
  return value;
}

function generateAgentFile(role: AgentRole): string {
  const lines: string[] = [
    "---",
    `description: ${yamlQuote(role.description)}`,
  ];

  // All ArcBridge roles are invokable via @mention, so they use subagent mode
  lines.push(`mode: subagent`);

  // Tool permissions — deny write/edit for read-only roles
  if (role.read_only) {
    lines.push("permission:");
    lines.push("  edit: deny");
    lines.push("  write: deny");
  }

  lines.push("---", "");
  lines.push(role.system_prompt, "");

  return lines.join("\n");
}

export class OpenCodeAdapter implements PlatformAdapter {
  platform = "opencode";

  generateProjectConfig(targetDir: string, config: ArcBridgeConfig): void {
    // Generate opencode.json (MCP config)
    const configPath = join(targetDir, "opencode.json");
    if (!existsSync(configPath)) {
      writeFileSync(configPath, generateOpenCodeJson(), "utf-8");
    } else {
      // Merge arcbridge config into existing opencode.json without overwriting user settings
      try {
        const existing = JSON.parse(readFileSync(configPath, "utf-8")) as Record<string, unknown>;
        let changed = false;

        // Ensure $schema is set
        if (!existing.$schema) {
          existing.$schema = "https://opencode.ai/config.json";
          changed = true;
        }

        // Ensure instructions array includes OPENCODE.md
        const instructions = existing.instructions as string[] | undefined;
        if (!Array.isArray(instructions)) {
          existing.instructions = ["OPENCODE.md"];
          changed = true;
        } else if (!instructions.includes("OPENCODE.md")) {
          instructions.push("OPENCODE.md");
          changed = true;
        }

        // Ensure mcp.arcbridge is present
        const mcp = existing.mcp as Record<string, unknown> | undefined;
        if (!mcp?.arcbridge) {
          existing.mcp = mcp ?? {};
          (existing.mcp as Record<string, unknown>).arcbridge = {
            type: "local",
            command: ["npx", "-y", "@arcbridge/mcp-server"],
          };
          changed = true;
        }

        if (changed) {
          writeFileSync(configPath, JSON.stringify(existing, null, 2) + "\n", "utf-8");
        }
      } catch {
        // Can't parse existing opencode.json — leave it alone
      }
    }

    // Generate OPENCODE.md (project instructions — opencode reads AGENTS.md by default,
    // but we use OPENCODE.md + the instructions config field to avoid colliding with Codex)
    const instructionsContent = generateInstructions(config);
    writeWithMarkerMerge(join(targetDir, "OPENCODE.md"), instructionsContent);
  }

  generateAgentConfigs(targetDir: string, roles: AgentRole[], options?: AdapterOptions): void {
    // Generate .opencode/agents/*.md (OpenCode subagents mapped from ArcBridge roles)
    const agentsDir = join(targetDir, ".opencode", "agents");
    mkdirSync(agentsDir, { recursive: true });

    for (const role of roles) {
      const content = generateAgentFile(role);
      writeFileSync(join(agentsDir, `${role.role_id}.md`), content, "utf-8");
    }

    // Generate skills under .opencode/skills/ (OpenCode loads from .opencode/skills/*/SKILL.md)
    const skillsDir = join(targetDir, ".opencode", "skills");
    generateOpenCodeSkills(skillsDir, options?.force);

    // Also generate shared .agents/skills/ (OpenCode loads these too)
    generateSkills(targetDir, options?.force);
  }
}

/**
 * Generate ArcBridge skills under .opencode/skills/.
 * OpenCode natively loads from .opencode/skills/<name>/SKILL.md.
 * Only writes if not present (preserves existing). Pass force=true to overwrite.
 */
function generateOpenCodeSkills(skillsDir: string, force = false): void {
  const SYNC_SKILL = `---
name: arcbridge-sync
description: Run the ArcBridge sync loop — reindex code, detect architecture drift, and update task statuses. Use after significant code changes or before completing a phase.
---

# ArcBridge Sync

Run the full sync loop to keep architecture docs and task statuses in sync with code changes.

## Steps

1. **Reindex** — \`arcbridge_reindex\` to update the symbol index with recent code changes
2. **Check drift** — \`arcbridge_check_drift\` to detect undeclared dependencies and missing modules
3. **Review tasks** — \`arcbridge_get_current_tasks\` to see if any tasks can be inferred as done
4. **Propose updates** — \`arcbridge_propose_arc42_update\` to generate documentation update proposals
`;

  const REVIEW_SKILL = `---
name: arcbridge-review
description: Run ArcBridge phase boundary reviews — drift check, quality scenario verification, and practice review across 5 dimensions. Use before completing a phase.
---

# ArcBridge Phase Review

Run the full review suite before completing a phase gate.

## Steps

1. **Drift check** — \`arcbridge_check_drift\` to catch undeclared dependencies and boundary violations
2. **Verify scenarios** — \`arcbridge_verify_scenarios\` to run linked tests for quality scenarios
3. **Practice review** — \`arcbridge_get_practice_review\` to review changes across architecture, security, testing, docs, and complexity
4. **Role checks** — optionally run \`arcbridge_run_role_check\` with specific roles (security-reviewer, quality-guardian)
5. **Complete phase** — if all checks pass, run \`arcbridge_complete_phase\` to validate gates and transition
`;

  const syncPath = join(skillsDir, "arcbridge-sync", "SKILL.md");
  if (force || !existsSync(syncPath)) {
    mkdirSync(join(skillsDir, "arcbridge-sync"), { recursive: true });
    writeFileSync(syncPath, SYNC_SKILL, "utf-8");
  }

  const reviewPath = join(skillsDir, "arcbridge-review", "SKILL.md");
  if (force || !existsSync(reviewPath)) {
    mkdirSync(join(skillsDir, "arcbridge-review"), { recursive: true });
    writeFileSync(reviewPath, REVIEW_SKILL, "utf-8");
  }
}
